# Generated by Django 4.0.6 on 2022-07-21 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videoService', '0002_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 19, 21, 57, 142426, tzinfo=utc)),
        ),
    ]
